#ifndef GRAPH_GRAMMAR_NATIVE_H
#define GRAPH_GRAMMAR_NATIVE_H

#pragma once

/* Generated by cbindgen from src/lib.rs. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/*
 Opaque stateful engine handle (exposed across the FFI as `Engine*`).
 */
typedef struct Engine Engine;

/*
 Returns the library version as a static, NUL-terminated C string.
 The returned pointer is owned by the library; do NOT free it.
 */
const char *gg_version(void);

/*
 Apply one rule to one graph. `rule_json` and `graph_json` are NUL-terminated
 UTF-8. On return `*out_json` points to a newly allocated NUL-terminated UTF-8
 result that the caller MUST release with `gg_string_free`.

 Returns 0 on success (the result envelope), or a non-zero code on error (the
 result is `{ "error": { code, detail } }`): 1 = bad input JSON,
 3 = unsupported feature, -1 = null argument or internal panic.
 */
int32_t gg_apply_rule(const char *rule_json, const char *graph_json, char **out_json);

/*
 Like `gg_apply_rule`, but with a seeded RNG (`seed`, a u32): stochastic match
 selection and random PropExprs (`randInt`/`randFloat`) are reproduced
 bit-for-bit against the TypeScript engine for the same seed. Same return-code
 and ownership contract as `gg_apply_rule`.
 */
int32_t gg_apply_rule_seeded(const char *rule_json,
                             const char *graph_json,
                             uint32_t seed,
                             char **out_json);

/*
 Free a string previously returned via an `out_json` out-parameter.
 Passing NULL is a no-op. Never call this on the `gg_version` pointer.
 */
void gg_string_free(char *s);

/*
 Create an engine from a grammar (JSON). `start_graph_json` may be NULL to use
 the grammar's own `start` axiom. On success returns a non-NULL handle; on
 error returns NULL and, if `err_out` is non-NULL, writes `{ "error": … }` to
 `*err_out` (release it with `gg_string_free`).
 */
Engine *gg_engine_new(const char *grammar_json, const char *start_graph_json, char **err_out);

/*
 Advance the engine one step. Writes the step result
 (`{ applied, ruleId?, createdNodes, … }`) to `*out_json`. Returns 0, or a
 non-zero error code (result is `{ "error": … }`). Release `*out_json` with
 `gg_string_free`.
 */
int32_t gg_engine_step(Engine *eng, char **out_json);

/*
 Run the engine until no rule applies or a bound is hit. `max_steps`: pass a
 negative value to use the grammar's `config.maxSteps`. Writes
 `{ "applied": <count> }` to `*out_json`. Returns 0 or an error code.
 */
int32_t gg_engine_run(Engine *eng, int32_t max_steps, char **out_json);

/*
 Snapshot the engine's current host graph as `{ nodes, edges }` to `*out_json`.
 Returns 0 or an error code. Release `*out_json` with `gg_string_free`.
 */
int32_t gg_engine_graph(Engine *eng, char **out_json);

/*
 Release an engine handle. Passing NULL is a no-op. Using the handle after
 this is undefined behaviour.
 */
void gg_engine_free(Engine *eng);

#endif  /* GRAPH_GRAMMAR_NATIVE_H */
