//! Conformance tests: the native port's output must match the TypeScript
//! engine's output for the same (rule, graph). Fixtures are generated by
//! `conformance/generate.ts` running the REAL engine. Regenerate with:
//!
//!   npx tsx conformance/generate.ts
//!
//! Graphs are compared up to ID-renaming of created elements (the engine's
//! `uid()` is volatile) and minus layout (`x`/`y`). Because both sides perform
//! the same add/delete operations in the same order, node/edge LISTS line up
//! positionally, so a positional walk recovers the id-isomorphism exactly.

use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

use serde_json::{json, Value};

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("conformance/fixtures")
}

fn read(name: &str) -> Value {
    let path = fixtures_dir().join(name);
    let text = fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path:?}: {e}"));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("parse {path:?}: {e}"))
}

fn arr(v: &Value, k: &str) -> Vec<Value> {
    v[k].as_array().cloned().unwrap_or_default()
}
fn s(v: &Value, k: &str) -> String {
    v[k].as_str().unwrap_or("").to_string()
}
fn props(v: &Value) -> Value {
    v.get("props").cloned().unwrap_or(json!({}))
}

/// Compare `got` (native) with `want` (engine) up to id-renaming. Returns Err
/// with a reason on divergence. `x`/`y` are ignored (renderer metadata).
fn graphs_equiv(got: &Value, want: &Value) -> Result<(), String> {
    let (gn, wn) = (arr(got, "nodes"), arr(want, "nodes"));
    if gn.len() != wn.len() {
        return Err(format!("node count {} vs {}", gn.len(), wn.len()));
    }
    // Position i in both lists is the same logical node (same op order).
    let mut id_map: HashMap<String, String> = HashMap::new();
    for (a, b) in gn.iter().zip(wn.iter()) {
        if s(a, "label") != s(b, "label") {
            return Err(format!("node label {} vs {}", s(a, "label"), s(b, "label")));
        }
        if props(a) != props(b) {
            return Err(format!("node props differ ({} vs {})", props(a), props(b)));
        }
        id_map.insert(s(a, "id"), s(b, "id"));
    }
    let (ge, we) = (arr(got, "edges"), arr(want, "edges"));
    if ge.len() != we.len() {
        return Err(format!("edge count {} vs {}", ge.len(), we.len()));
    }
    for (a, b) in ge.iter().zip(we.iter()) {
        if s(a, "label") != s(b, "label") || a["directed"] != b["directed"] || props(a) != props(b) {
            return Err("edge label/directed/props differ".to_string());
        }
        if id_map.get(&s(a, "source")).cloned().unwrap_or_default() != s(b, "source")
            || id_map.get(&s(a, "target")).cloned().unwrap_or_default() != s(b, "target")
        {
            return Err("edge endpoint mapping differs".to_string());
        }
    }
    Ok(())
}

fn run_fixture(name: &str) {
    let input = read(&format!("{name}.input.json"));
    let expected = read(&format!("{name}.expected.json"));

    // Engine fixtures (multi-step run) carry a `grammar`; rule fixtures a `rule`.
    if let Some(grammar) = input.get("grammar") {
        let grammar_json = serde_json::to_string(grammar).unwrap();
        let (graph_json, applied) = graph_grammar::run_grammar(&grammar_json, None, None)
            .unwrap_or_else(|e| panic!("{name}: run errored (code {}): {}", e.code, e.detail));
        let got: Value = serde_json::from_str(&graph_json).unwrap();
        graphs_equiv(&got, &expected)
            .unwrap_or_else(|e| panic!("{name}: native run diverged from the TS engine: {e}"));
        if let Some(want_applied) = expected.get("applied").and_then(|a| a.as_i64()) {
            assert_eq!(applied, want_applied, "{name}: applied-step count diverged");
        }
        return;
    }

    let rule_json = serde_json::to_string(&input["rule"]).unwrap();
    let graph_json = serde_json::to_string(&input["graph"]).unwrap();

    // Seeded fixtures take the stochastic path; deterministic ones the plain one.
    let out = match input.get("seed").and_then(|s| s.as_u64()) {
        Some(seed) => graph_grammar::apply_rule_seeded(&rule_json, &graph_json, seed as u32),
        None => graph_grammar::apply_rule(&rule_json, &graph_json),
    }
    .unwrap_or_else(|e| panic!("{name}: apply errored (code {}): {}", e.code, e.detail));
    let envelope: Value = serde_json::from_str(&out).unwrap();

    assert_eq!(envelope["applied"], json!(true), "{name}: expected a match to apply");

    graphs_equiv(&envelope["graph"], &expected)
        .unwrap_or_else(|e| panic!("{name}: native output diverged from the TS engine: {e}"));
}

/// Discover every `*.input.json` fixture so adding a fixture needs no test edit.
fn fixture_names() -> Vec<String> {
    let mut names: Vec<String> = fs::read_dir(fixtures_dir())
        .expect("fixtures dir exists (run `npx tsx conformance/generate.ts`)")
        .filter_map(|e| e.ok())
        .filter_map(|e| e.file_name().into_string().ok())
        .filter_map(|f| f.strip_suffix(".input.json").map(str::to_string))
        .collect();
    names.sort();
    names
}

#[test]
fn all_fixtures_match_ts_engine() {
    let names = fixture_names();
    assert!(!names.is_empty(), "no fixtures found");
    for name in &names {
        run_fixture(name);
        eprintln!("ok: {name}");
    }
}

/// The zod-derived schema is enforced at the boundary: structurally-invalid
/// input is rejected (code 1) instead of silently accepted.
#[test]
fn rejects_schema_invalid_input() {
    let graph = r#"{"nodes":[],"edges":[]}"#;
    // A rule missing the required `rhs`.
    let bad_rule = r#"{"id":"r","name":"r","enabled":true,"weight":1,"probability":1,
        "priority":0,"maxApplications":0,"lhs":{"nodes":[],"edges":[]},"morphism":[],"embedding":[]}"#;
    let err = graph_grammar::apply_rule(bad_rule, graph).expect_err("rule should be rejected");
    assert_eq!(err.code, 1, "detail: {}", err.detail);
    assert!(err.detail.contains("rule"), "detail: {}", err.detail);

    // A grammar missing the required `config`.
    let bad_grammar = r#"{"id":"g","name":"g","rules":[],"start":{"nodes":[],"edges":[]}}"#;
    let err =
        graph_grammar::run_grammar(bad_grammar, None, None).expect_err("grammar should be rejected");
    assert_eq!(err.code, 1, "detail: {}", err.detail);
}
